const user = [
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
];
 const mentor = [
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
    { id: 1, name: "eshmat" },
];
export { user, mentor } 
export default user;